# Summary

In this notebook, I try to use my rotation and property extraction functions to test the invariance of the QTAIM quadrupole to rotation. I start by taking the geometry with the first atom zeroed at the origin and determining the rotation to align it with the reoriented geometry. Then, I take that rotation, and rotate the elements that make up the substituent quadrupole matrix with it.

This did not work, and the quadrupole exhibits large change.

In [1]:
import sys
sys.path.append(sys.path[0].replace('Development Notebooks',''))
from subproptools import qtaimExtract as qt
from subproptools import subreor as sr
import pandas as pd
import numpy as np
import math

Initially, I determine the geometry shift needed to go from the original geometry to the modified geometry
Note that I may want to do one where the atom is already at the origin and don't need to shift that way, just rotate


In [3]:
original_geom = qt.get_xyz("Data/SubH_CFHCH3_wb97xd_aug-cc-pvtz_zeroorig")['xyz']
rotated_geom = qt.get_xyz("Data/SubH_CFHCH3_reor_wb97xd_aug-cc-pvtz")['xyz']

In [ ]:
original_geom

array([[ 0.       ,  0.       ,  0.       ],
       [ 0.0515014,  1.1991928,  1.677408 ],
       [ 0.0515014,  1.1991928, -1.677408 ],
       [ 2.124002 , -1.8984325,  0.       ],
       [ 2.033135 , -3.0940259,  1.6729925],
       [ 2.033135 , -3.0940259, -1.6729925],
       [ 3.9347699, -0.9139359,  0.       ],
       [-2.3164504, -1.2373688,  0.       ]], dtype=float32)

In [4]:
rotated_geom

array([[ 0.        ,  0.        ,  0.        ],
       [-2.0626228 ,  0.        ,  0.        ],
       [ 0.66564846,  1.952261  ,  0.        ],
       [ 1.0506991 , -1.4683454 ,  2.203502  ],
       [ 0.38753182, -3.416487  ,  2.164018  ],
       [ 3.108622  , -1.4693639 ,  2.164018  ],
       [ 0.4331082 , -0.6052657 ,  3.97036   ],
       [ 0.7772349 , -1.0861813 , -2.2612255 ]], dtype=float32)

In [6]:
negXAtom=2
t_xyz=sr._set_origin(original_geom,1).T
t_xyz.T

array([[ 0.       ,  0.       ,  0.       ],
       [ 0.0515014,  1.1991928,  1.677408 ],
       [ 0.0515014,  1.1991928, -1.677408 ],
       [ 2.124002 , -1.8984325,  0.       ],
       [ 2.033135 , -3.0940259,  1.6729925],
       [ 2.033135 , -3.0940259, -1.6729925],
       [ 3.9347699, -0.9139359,  0.       ],
       [-2.3164504, -1.2373688,  0.       ]], dtype=float32)

In [7]:
d = t_xyz[0,negXAtom-1]/math.sqrt(t_xyz[0,negXAtom-1]**2 + t_xyz[1,negXAtom-1]**2)
s = t_xyz[1,negXAtom-1]/math.sqrt(t_xyz[0,negXAtom-1]**2 + t_xyz[1,negXAtom-1]**2)
G1 = np.array([[d,s,0.],[-s,d,0.],[0.,0.,1.]])
zero_y = np.matmul(G1,t_xyz)
zero_y.T

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.20029816e+00, -2.19229001e-18,  1.67740798e+00],
       [ 1.20029816e+00, -2.19229001e-18, -1.67740798e+00],
       [-1.80554923e+00, -2.20350229e+00,  0.00000000e+00],
       [-3.00394037e+00, -2.16401846e+00,  1.67299247e+00],
       [-3.00394037e+00, -2.16401846e+00, -1.67299247e+00],
       [-7.44264359e-01, -3.97036060e+00,  0.00000000e+00],
       [-1.33562163e+00,  2.26122505e+00,  0.00000000e+00]])

In [8]:
d = zero_y[0,negXAtom-1]/math.sqrt(zero_y[0,negXAtom-1]**2 + zero_y[2,negXAtom-1]**2)
s = zero_y[2,negXAtom-1]/math.sqrt(zero_y[0,negXAtom-1]**2 + zero_y[2,negXAtom-1]**2)
G2 = np.array([[d,0,s],[0,1,0],[-s,0,d]])
G2


array([[ 0.58192807,  0.        ,  0.81324026],
       [ 0.        ,  1.        ,  0.        ],
       [-0.81324026,  0.        ,  0.58192807]])

In [9]:
onx = np.matmul(G2,zero_y)
onx.T

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.06262290e+00, -2.19229001e-18,  3.17299601e-17],
       [-6.65648509e-01, -2.19229001e-18, -1.95226158e+00],
       [-1.05069978e+00, -2.20350229e+00,  1.46834533e+00],
       [-3.87532393e-01, -2.16401846e+00,  3.41648653e+00],
       [-3.10862205e+00, -2.16401846e+00,  1.46936397e+00],
       [-4.33108322e-01, -3.97036060e+00,  6.05265741e-01],
       [-7.77235716e-01,  2.26122505e+00,  1.08618128e+00]])

In [10]:
G3 = np.array([[-1,0,0],[0,1,0],[0,0,-1]])
onxZeroZ = np.matmul(G3,onx)

In [11]:
G4 = np.array([[1,0,0],[0,0,1],[0,-1,0]])
np.matmul(G4,onxZeroZ).T

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.06262290e+00, -3.17299601e-17,  2.19229001e-18],
       [ 6.65648509e-01,  1.95226158e+00,  2.19229001e-18],
       [ 1.05069978e+00, -1.46834533e+00,  2.20350229e+00],
       [ 3.87532393e-01, -3.41648653e+00,  2.16401846e+00],
       [ 3.10862205e+00, -1.46936397e+00,  2.16401846e+00],
       [ 4.33108322e-01, -6.05265741e-01,  3.97036060e+00],
       [ 7.77235716e-01, -1.08618128e+00, -2.26122505e+00]])

In [12]:
Ga = np.matmul(G2,G1)
Gb = np.matmul(G3,Ga)
G = np.matmul(G4,Gb)
rotated_geom - np.matmul(G,t_xyz).T #all ~0 - rotation good

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.09497198e-07,  3.17299601e-17, -2.19229001e-18],
       [-4.88659810e-08, -6.07043552e-07, -2.19229001e-18],
       [-6.64491231e-07, -7.81771536e-08, -3.45336598e-07],
       [-5.75582118e-07, -4.52501999e-07, -5.44290907e-07],
       [ 2.16602540e-08,  4.09296774e-08, -5.44290907e-07],
       [-1.11741262e-07,  6.40324479e-08, -5.61793439e-07],
       [-8.04087448e-07, -3.72152065e-09, -4.11088969e-07]])

Here, we've found the rotation necessary to identify the quadupole

In [13]:
sumFile = open('Data/SubH_CFHCH3_wb97xd_aug-cc-pvtz_zeroorig'+".sum","r") #open file, read lines, close file
data = sumFile.readlines()
sumFile.close()

In [15]:
atomTest = qt.get_atomic_props(data)
list(atomTest['C1'].keys())
for key in atomTest:
    atomTest[key].update({'quadContrib':qt._get_atomic_quad_contrib(atomTest[key])})

In [16]:
def get_needed_for_quad(atomTest,atomLabel,rotationMatrix = np.array([[1.,0.,0.],[0.,1.,0.],[0.,0.,1.]])):
    atom_from_sum_quad = np.array([[atomTest[atomLabel]['Q_XX'][0], atomTest[atomLabel]['Q_XY'][0], atomTest[atomLabel]['Q_XZ'][0] ],
                              [ atomTest[atomLabel]['Q_XY'][0],atomTest[atomLabel]['Q_YY'][0],atomTest[atomLabel]['Q_YZ'][0]],
                              [ atomTest[atomLabel]['Q_XZ'][0],atomTest[atomLabel]['Q_YZ'][0],atomTest[atomLabel]['Q_ZZ'][0]]])
    atom_from_sum_mu_intra = np.array([atomTest[atomLabel]['Mu_Intra_X'][0], atomTest['C1']['Mu_Intra_Y'][0], atomTest['C1']['Mu_Intra_Z'][0]])
    atom_from_sum_xyz = np.array(atomTest[atomLabel]['xyz'])
    atom_from_sum_r2 = atomTest[atomLabel]['R+2'][0]
    atomCharge = atomTest[atomLabel]['q'][0]
    rotQuad = np.matmul(rotationMatrix,atom_from_sum_quad)
    rotMuIntra = np.matmul(rotationMatrix,atom_from_sum_mu_intra)
    rotCoords = np.matmul(rotationMatrix,atom_from_sum_xyz)

    return {'q':[atomCharge],'Q_XX':[rotQuad[0,0]], 'Q_XY':[rotQuad[0,1]],
            'Q_XZ':[rotQuad[0,2]],'Q_YY':[rotQuad[1,1]],'Q_YZ':[rotQuad[1,2]],
            'Q_ZZ':[rotQuad[2,2]], 'Mu_Intra_X':[rotMuIntra[0]], 'Mu_Intra_Y':[rotMuIntra[1]],
            'Mu_Intra_Z':[rotMuIntra[2]],'xyz':rotCoords, 'R+2':[atom_from_sum_r2]}

In [17]:
def get_trial_needed_for_quad(atomTest,atomLabel,rotationMatrix = np.array([[1.,0.,0.],[0.,1.,0.],[0.,0.,1.]])):
    #no rotation for quadrupole here - to be used woth trial_atomic_contrib_rotation
    atom_from_sum_quad = np.array([[atomTest[atomLabel]['Q_XX'][0], atomTest[atomLabel]['Q_XY'][0], atomTest[atomLabel]['Q_XZ'][0] ],
                              [ atomTest[atomLabel]['Q_XY'][0],atomTest[atomLabel]['Q_YY'][0],atomTest[atomLabel]['Q_YZ'][0]],
                              [ atomTest[atomLabel]['Q_XZ'][0],atomTest[atomLabel]['Q_YZ'][0],atomTest[atomLabel]['Q_ZZ'][0]]])
    atom_from_sum_mu_intra = np.array([atomTest[atomLabel]['Mu_Intra_X'][0], atomTest['C1']['Mu_Intra_Y'][0], atomTest['C1']['Mu_Intra_Z'][0]])
    atom_from_sum_xyz = np.array(atomTest[atomLabel]['xyz'])
    atom_from_sum_r2 = atomTest[atomLabel]['R+2'][0]
    atomCharge = atomTest[atomLabel]['q'][0]
    rotQuad = np.matmul(rotationMatrix,atom_from_sum_quad)
    rotMuIntra = np.matmul(rotationMatrix,atom_from_sum_mu_intra)
    rotCoords = np.matmul(rotationMatrix,atom_from_sum_xyz)

    return {'q':[atomCharge],'Q_XX':[atom_from_sum_quad[0,0]], 'Q_XY':[atom_from_sum_quad[0,1]],
            'Q_XZ':[atom_from_sum_quad[0,2]],'Q_YY':[atom_from_sum_quad[1,1]],'Q_YZ':[atom_from_sum_quad[1,2]],
            'Q_ZZ':[atom_from_sum_quad[2,2]], 'Mu_Intra_X':[rotMuIntra[0]], 'Mu_Intra_Y':[rotMuIntra[1]],
            'Mu_Intra_Z':[rotMuIntra[2]],'xyz':rotCoords, 'R+2':[atom_from_sum_r2]}

In [18]:
get_needed_for_quad(atomTest,'C1',G)

{'q': [0.6105604278],
 'Q_XX': [-0.3874464545043634],
 'Q_XY': [0.11718142837956236],
 'Q_XZ': [0.46096921493966925],
 'Q_YY': [-0.16579553436079722],
 'Q_YZ': [0.3312269082600497],
 'Q_ZZ': [-0.0016155026980413294],
 'Mu_Intra_X': [0.20475539275023455],
 'Mu_Intra_Y': [-0.2859994999118161],
 'Mu_Intra_Z': [-0.561843537059774],
 'xyz': array([0., 0., 0.]),
 'R+2': [7.0866464632]}

In [ ]:
C1TestQuad = qt.get_atomic_quad_contrib(get_needed_for_quad(atomTest,'C1',G))
H3TestQuad = qt.get_atomic_quad_contrib(get_needed_for_quad(atomTest,'H3',G))
C4TestQuad = qt.get_atomic_quad_contrib(get_needed_for_quad(atomTest,'C4',G))
H5TestQuad = qt.get_atomic_quad_contrib(get_needed_for_quad(atomTest,'H5',G))
H6TestQuad = qt.get_atomic_quad_contrib(get_needed_for_quad(atomTest,'H6',G))
H7TestQuad = qt.get_atomic_quad_contrib(get_needed_for_quad(atomTest,'H7',G))
F8TestQuad = qt.get_atomic_quad_contrib(get_needed_for_quad(atomTest,'F8',G))
QyyTest = C1TestQuad['Q_yy'][0] + H3TestQuad['Q_yy'][0] + C4TestQuad['Q_yy'][0] + H5TestQuad['Q_yy'][0] + H6TestQuad['Q_yy'][0] + H7TestQuad['Q_yy'][0] + F8TestQuad['Q_yy'][0]
QxxTest = C1TestQuad['Q_xx'][0] + H3TestQuad['Q_xx'][0] + C4TestQuad['Q_xx'][0] + H5TestQuad['Q_xx'][0] + H6TestQuad['Q_xx'][0] + H7TestQuad['Q_xx'][0] + F8TestQuad['Q_xx'][0]
QzzTest = C1TestQuad['Q_zz'][0] + H3TestQuad['Q_zz'][0] + C4TestQuad['Q_zz'][0] + H5TestQuad['Q_zz'][0] + H6TestQuad['Q_zz'][0] + H7TestQuad['Q_zz'][0] + F8TestQuad['Q_zz'][0]
QxxTest+QyyTest+QzzTest

0.0

In [ ]:
#Wanted to try rotating second moment later after constructing it from .sum file properties
#This does not seem to work either
C1TestQuad2 = qt.trial_atomic_contrib_rotation(get_trial_needed_for_quad(atomTest,'C1',G),G)
H3TestQuad2 = qt.trial_atomic_contrib_rotation(get_trial_needed_for_quad(atomTest,'H3',G),G)
C4TestQuad2 = qt.trial_atomic_contrib_rotation(get_trial_needed_for_quad(atomTest,'C4',G),G)
H5TestQuad2 = qt.trial_atomic_contrib_rotation(get_trial_needed_for_quad(atomTest,'H5',G),G)
H6TestQuad2 = qt.trial_atomic_contrib_rotation(get_trial_needed_for_quad(atomTest,'H6',G),G)
H7TestQuad2 = qt.trial_atomic_contrib_rotation(get_trial_needed_for_quad(atomTest,'H7',G),G)
F8TestQuad2 = qt.trial_atomic_contrib_rotation(get_trial_needed_for_quad(atomTest,'F8',G),G)

C1TestQuad2['Q_xx'][0] + H3TestQuad2['Q_xx'][0] + C4TestQuad2['Q_xx'][0] + H5TestQuad2['Q_xx'][0] + H6TestQuad2['Q_xx'][0] + H7TestQuad2['Q_xx'][0] + F8TestQuad2['Q_xx'][0]
C1TestQuad2['Q_yy'][0] + H3TestQuad2['Q_yy'][0] + C4TestQuad2['Q_yy'][0] + H5TestQuad2['Q_yy'][0] + H6TestQuad2['Q_yy'][0] + H7TestQuad2['Q_yy'][0] + F8TestQuad2['Q_yy'][0]

12.810884950106992

In [ ]:
sumFile = open('SubH_CFHCH3_reor_wb97xd_aug-cc-pvtz'+".sum","r") #open file, read lines, close file
dataReor = sumFile.readlines()
sumFile.close()
atomReor = qt.get_atomic_props(dataReor)
for key in atomReor:
    atomReor[key].update({'quadContrib':qt.get_atomic_quad_contrib(atomReor[key])})
qt.get_sub_props(atomReor,[1,3,4,5,6,7,8],["C1","H2","H3","C4","H5","H6","H7","F8"])    

['Atom', 'Charge', 'X', 'Y', 'Z']
['Atom', 'q(A)', 'L(A)', 'K(A)', 'K_Scaled(A)', '|Mu_Intra(A)|']
['Atom', 'Mu_Intra_X(A)', 'Mu_Bond_X(A)', 'Mu_X(A)']
['Atom', 'Mu_Intra_Y(A)', 'Mu_Bond_Y(A)', 'Mu_Y(A)']
['Atom', 'Mu_Intra_Z(A)', 'Mu_Bond_Z(A)', 'Mu_Z(A)']
['Atom', '|Mu_Intra(A)|', '|Mu_Bond(A)|', '|Mu(A)|']
['Atom', 'Q_XX(A)', 'Q_XY(A)', 'Q_XZ(A)', 'Q_YY(A)', 'Q_YZ(A)', 'Q_ZZ(A)']
['Atom', 'R-2(A)', 'R-1(A)', 'R0(A)', 'R+1(A)', 'R+2(A)']
['Atom', 'Area(A)', 'Vol(A)', 'N(Vol(A))', 'N(Vol(A))/Vol(A)', '%N(Vol(A))']


{'q': [-0.012042308080000064],
 'K': [177.45030553599003],
 'K_Scaled': [-178.44807629584],
 'Mu_Intra_X': [0.16653271575],
 'Mu_Intra_Y': [-0.41236599408389996],
 'Mu_Intra_Z': [-0.9758305059259],
 'Mu_Bond_X': [-0.47675302472190006],
 'Mu_Bond_Y': [0.6787360862049749],
 'Mu_Bond_Z': [1.68197961953125],
 'Mu_X': [-0.31022030898],
 'Mu_Y': [0.26637009212429996],
 'Mu_Z': [0.7061491135953],
 'Q_xx': [1.2625756432120898],
 'Q_xy': [0.44917096416297386],
 'Q_xz': [0.8787896492323091],
 'Q_yy': [0.4538377141843203],
 'Q_yz': [-1.2753249463521499],
 'Q_zz': [-1.7164133573964084],
 'Vol': [423.130124775],
 '|Mu_Intra|': [1.0723917356952501],
 '|Mu_Bond|': [0.8159878900531444]}

In [ ]:
atomReor['C1']['quadContrib']['Q_xx'][0] + atomReor['H3']['quadContrib']['Q_xx'][0] + atomReor['C4']['quadContrib']['Q_xx'][0] + atomReor['H5']['quadContrib']['Q_xx'][0] + atomReor['H6']['quadContrib']['Q_xx'][0] +atomReor['H7']['quadContrib']['Q_xx'][0] + atomReor['F8']['quadContrib']['Q_xx'][0]

1.2625756432120898