In [1]:
import sys
sys.path.append(sys.path[0].replace('/Development Notebooks',''))
from subproptools import qtaimExtract as qt
from subproptools import subreor as sr
import pandas as pd

In [2]:
sr.rotate_substituent('HC-C-C-CO_wb97xd_aug-cc-pvtz',originAtom=1,negXAtom=5)

IndexError: index 4 is out of bounds for axis 1 with size 4

In [8]:
sumFileNoExt = 'HC-C-C-CO_wb97xd_aug-cc-pvtz'
originAtom = 1
negXAtom = 5
posYAtom = 0

In [9]:
sumFile = open(sumFileNoExt+".sum","r")
data = sumFile.readlines()
sumFile.close()

In [10]:
atomDict = qt.get_atomic_props(data)

In [11]:
molecule_xyz = qt.get_xyz(sumFileNoExt)

In [12]:
negXAtomLabel = molecule_xyz['Atoms'][negXAtom-1]

In [13]:
attachedAtom = molecule_xyz['Atoms'][originAtom-1]

In [16]:
molecule_orig = sr._set_origin(molecule_xyz['xyz'],originAtom)
molecule_orig

array([[ 0.        ,  0.        ,  0.        ],
       [ 2.1014504 , -1.1039778 , -1.238721  ],
       [-0.40703416,  2.7398713 , -0.7853528 ],
       [-2.268362  , -1.6346834 , -0.6241007 ],
       [ 0.33981407, -0.06584188,  2.0491657 ],
       [-2.078061  ,  3.5036252 ,  0.14709377],
       [-0.68590236,  2.8535416 , -2.824773  ],
       [ 1.191238  ,  3.933376  , -0.2754068 ],
       [-2.6213746 , -1.6089971 , -2.6546714 ],
       [-1.9336425 , -3.5812733 , -0.04747176],
       [-3.9492502 , -0.93698174,  0.34041685],
       [ 4.461873  , -0.20218003, -0.44448355],
       [ 4.662208  , -0.32332978,  1.6157975 ],
       [ 4.7965984 ,  1.7568655 , -1.021615  ],
       [ 5.893173  , -1.3914044 , -1.3194331 ]], dtype=float32)

In [18]:
molecule_xaxis = sr._set_xaxis(molecule_orig,negXAtom)

In [19]:
molecule_xaxis

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 8.42825324e-01, -6.84081135e-01,  2.44764564e+00],
       [ 9.27744281e-01,  2.61241854e+00, -7.77116678e-01],
       [ 9.34502147e-01, -2.03632581e+00, -1.78528449e+00],
       [-2.07819367e+00, -5.34475225e-18,  6.79426303e-18],
       [ 3.05755974e-01,  3.04436329e+00, -2.69327481e+00],
       [ 2.98787840e+00,  2.67096690e+00, -7.28713390e-01],
       [ 2.01393937e-01,  4.08815611e+00,  4.61263920e-01],
       [ 2.99524649e+00, -2.07825886e+00, -1.79362636e+00],
       [ 2.49523750e-01, -3.88370303e+00, -1.19219721e+00],
       [ 2.80410634e-01, -1.67110310e+00, -3.70394115e+00],
       [-2.97709832e-01,  6.50252412e-01,  4.43117300e+00],
       [-2.36580907e+00,  5.69422577e-01,  4.30467575e+00],
       [ 2.78695008e-01,  2.63720011e+00,  4.48387498e+00],
       [ 2.93303385e-01, -2.44995297e-01,  6.18549520e+00]])

In [21]:
ccProps = qt.get_cc_props(sumFileNoExt,attachedAtom)

In [23]:
vscc = qt.identify_vscc(ccProps,atomDict,attachedAtom)

In [24]:
len(vscc)

0

In [25]:
bcpsToMatch = sr._find_bcp_match(data,atomDict[attachedAtom]['xyz'],negXAtomLabel,attachedAtom,atomDict)

IndexError: index 4 is out of bounds for axis 1 with size 4

In [26]:
originAtomXYZ = atomDict[attachedAtom]['xyz']
originAtomLabel = attachedAtom

In [28]:
originBCPs = qt._find_connected(data,negXAtomLabel,originAtomLabel)
bcpPropDict = {}

In [29]:
originBCPs

[['O2', 'C1'], ['C3', 'C1'], ['C1', 'C4']]

In [30]:
sr._find_clockwise_rot(bcpPropDict,originAtomLabel,negXAtomLabel,atomDict,originAtomXYZ)

{}

In [31]:
crossDict = {}

In [32]:
atoms = list(atomDict.keys())

In [33]:
atoms

['C1',
 'O2',
 'C3',
 'C4',
 'H5',
 'H6',
 'H7',
 'H8',
 'H9',
 'H10',
 'H11',
 'C12',
 'H13',
 'H14',
 'H15']

In [34]:
neg_x_index = atoms.index(negXAtomLabel)

In [35]:
neg_x_index

4

In [38]:
bcpPropDict

{'O2-C1': {'xyz': array([-0.03907469, -0.37761442,  0.18549961]),
  'rho': [0.26264450199],
  'lambda1': [-0.5053165188],
  'lambda2': [-0.48923995813],
  'lambda3': [0.47486662401],
  'DelSqRho': [-0.51968985292],
  'Ellipticity': [0.032860277254],
  'V': [-0.60840996919],
  'G': [0.23924375298],
  'H': [-0.36916621621]},
 'C3-C1': {'xyz': array([-0.98684975,  1.36065504,  0.19451931]),
  'rho': [0.25378261485],
  'lambda1': [-0.51215382644],
  'lambda2': [-0.49479468986],
  'lambda3': [0.35306745538],
  'DelSqRho': [-0.65388106093],
  'Ellipticity': [0.035083514291],
  'V': [-0.27927754364],
  'G': [0.057903639205],
  'H': [-0.22137390443500002]},
 'C1-C4': {'xyz': array([-1.94066576, -0.84823262,  0.27176114]),
  'rho': [0.25796590264],
  'lambda1': [-0.52555114417],
  'lambda2': [-0.50709179364],
  'lambda3': [0.34722707546],
  'DelSqRho': [-0.68541586235],
  'Ellipticity': [0.036402384666],
  'V': [-0.28822800135],
  'G': [0.058437017884],
  'H': [-0.229790983466]}}

In [40]:
crossDict = {}
atoms = list(atomDict.keys())
neg_x_index = atoms.index(negXAtomLabel)
neg_x_index


4

In [43]:
key1 = list(bcpPropDict.keys())[0]
key2 = list(bcpPropDict.keys())[1]

In [44]:
import numpy as np
to_rotate = np.vstack((originAtomXYZ,atomDict[negXAtomLabel]['xyz'],bcpPropDict[key1]['xyz'],bcpPropDict[key2]['xyz']))

In [47]:
orig_geom = sr._set_origin(to_rotate,1)
orig_geom

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.33981406, -0.06584188,  2.04916577],
       [ 0.7500983 , -0.36033332, -0.41031673],
       [-0.19767677,  1.37793615, -0.40129703]])

In [50]:
sr._set_xaxis(orig_geom,2)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.07819371e+00, -3.48211853e-18, -3.71782265e-17],
       [ 2.70517630e-01, -2.11069841e-01,  8.62042407e-01],
       [ 4.71670847e-01,  1.31517465e+00, -3.82969556e-01]])