In [2]:
import sys
sys.path.append(sys.path[0].replace('/Development Notebooks',''))
from subproptools import qtaimExtract as qt
from subproptools import subreor as sr
import pandas as pd


# Summary

Here, I'm going through the version of rotate_substituent fo subreor.py as of June 28 to try to see if the bcp mapping code works for one substituent, using a default stat dictionary (from transferability paper, SubH bcp data)

In [2]:
molecule_xyz = qt.get_xyz('SubCH3_CFH2_anti2146_reor')
molecule_xyz

['Atom', 'Charge', 'X', 'Y', 'Z']


{'xyz': array([[ 0.        ,  0.        ,  0.        ],
        [-2.0632465 ,  0.        ,  0.        ],
        [ 0.6614873 ,  0.        , -1.954334  ],
        [ 1.0429549 , -2.2175765 ,  1.4540887 ],
        [ 0.41988203, -3.9796915 ,  0.58540124],
        [ 3.1010463 , -2.183896  ,  1.4541756 ],
        [ 0.38320056, -2.183896  ,  3.4035687 ],
        [ 0.7870294 ,  2.2448492 ,  1.0972787 ]], dtype=float32),
 'Atoms': 0    C1
 1    H2
 2    H3
 3    C4
 4    H5
 5    H6
 6    H7
 7    F8
 Name: Atom, dtype: object}

In [3]:
molecule_orig = sr._set_origin(molecule_xyz['xyz'],1)
molecule_orig

array([[ 0.        ,  0.        ,  0.        ],
       [-2.0632465 ,  0.        ,  0.        ],
       [ 0.6614873 ,  0.        , -1.954334  ],
       [ 1.0429549 , -2.2175765 ,  1.4540887 ],
       [ 0.41988203, -3.9796915 ,  0.58540124],
       [ 3.1010463 , -2.183896  ,  1.4541756 ],
       [ 0.38320056, -2.183896  ,  3.4035687 ],
       [ 0.7870294 ,  2.2448492 ,  1.0972787 ]], dtype=float32)

In [4]:
molecule_xaxis = sr._set_xaxis(molecule_orig,2)
molecule_xaxis

here


array([[ 0.        ,  0.        ,  0.        ],
       [-2.06324649,  0.        ,  0.        ],
       [ 0.66148728,  0.        , -1.95433402],
       [ 1.04295492, -2.2175765 ,  1.45408869],
       [ 0.41988203, -3.97969151,  0.58540124],
       [ 3.10104632, -2.18389606,  1.45417559],
       [ 0.38320056, -2.18389606,  3.40356874],
       [ 0.78702939,  2.24484921,  1.09727871]])

In [5]:
negXAtomLabel = molecule_xyz['Atoms'][2-1]
sumFile = open('SubCH3_CFH2_anti2146_reor'+".sum","r") #open file, read lines, close file
data = sumFile.readlines()
sumFile.close()
atomDict = qt.get_atomic_props(data)
atomDict

['Atom', 'Charge', 'X', 'Y', 'Z']
['Atom', 'q(A)', 'L(A)', 'K(A)', 'K_Scaled(A)', '|Mu_Intra(A)|']
['Atom', 'Mu_Intra_X(A)', 'Mu_Bond_X(A)', 'Mu_X(A)']
['Atom', 'Mu_Intra_Y(A)', 'Mu_Bond_Y(A)', 'Mu_Y(A)']
['Atom', 'Mu_Intra_Z(A)', 'Mu_Bond_Z(A)', 'Mu_Z(A)']
['Atom', '|Mu_Intra(A)|', '|Mu_Bond(A)|', '|Mu(A)|']
['Atom', 'Q_XX(A)', 'Q_XY(A)', 'Q_XZ(A)', 'Q_YY(A)', 'Q_YZ(A)', 'Q_ZZ(A)']
['Atom', 'R-2(A)', 'R-1(A)', 'R0(A)', 'R+1(A)', 'R+2(A)']
['Atom', 'Area(A)', 'Vol(A)', 'N(Vol(A))', 'N(Vol(A))/Vol(A)', '%N(Vol(A))']


{'C1': {'xyz': array([0., 0., 0.]),
  'q': [0.6181000154],
  'K': [37.399461789],
  'K_Scaled': [-37.611585114],
  'Mu_Intra_X': [0.20429893848],
  'Mu_Intra_Y': [0.55036571736],
  'Mu_Intra_Z': [0.28413900603],
  'Mu_Bond_X': [-0.15693694296],
  'Mu_Bond_Y': [-0.56007812492],
  'Mu_Bond_Z': [-0.2187898453],
  'Mu_X': [0.04736199552],
  'Mu_Y': [-0.0097124075554],
  'Mu_Z': [0.065349160734],
  '|Mu_Intra|': [0.65220813691],
  '|Mu_Bond|': [0.62143841729],
  '|Mu|': [0.08128961981],
  'Q_XX': [-0.42620547034],
  'Q_XY': [0.40159459646],
  'Q_XZ': [0.20294321691],
  'Q_YY': [0.7118632802],
  'Q_YZ': [0.5568112971],
  'Q_ZZ': [-0.28565780986],
  'R+2': [7.0525047078],
  'R+1': [4.995993954],
  'Vol': [50.594926203],
  'quadContrib': {'Q_xx': [-0.21310273516999967],
   'Q_xy': [0.20079729823000003],
   'Q_xz': [0.101471608455],
   'Q_yy': [0.35593164010000056],
   'Q_yz': [0.27840564855],
   'Q_zz': [-0.1428289049299991]}},
 'H2': {'xyz': array([-2.06324645,  0.        ,  0.        ]),
  '

In [4]:
# sr._get_ref_bcps('SubH_CFHCH3_reor_wb97xd_aug-cc-pvtz',[['C1','H3'],['C1','C4'],['C1','F8']],originAtom='C1')
atType = ''.join([i for i in 'As1' if not i.isdigit()])
atType
sumFile = open('SubH_AsO-C6H5-2_wb97xd_aug-cc-pvtz'+".sum",'r')
data = sumFile.readlines()
sumFile.close()
atomDict = qt.get_atomic_props(data)

In [24]:
sr._find_bcp_match(data,atomDict['As1']['xyz'],'H2','As1')

{'C14-As1': {'xyz': array([ 0.        , -1.22029984, -0.63095572]),
  'rho': [0.15290533046],
  'lambda1': [-0.2081819311],
  'lambda2': [-0.19345355996],
  'lambda3': [0.29148410764],
  'DelSqRho': [-0.11015138342],
  'Ellipticity': [0.076133885246],
  'V': [-0.17413690547],
  'G': [0.073299529808],
  'H': [-0.10083737566199999]},
 'As1-O25': {'xyz': array([ 0.        , -3.44111487, -0.31160667]),
  'rho': [0.22384375416],
  'lambda1': [-0.3322117103],
  'lambda2': [-0.33056191378],
  'lambda3': [1.3368750801],
  'DelSqRho': [0.67410145607],
  'Ellipticity': [0.0049908850692],
  'V': [-0.51474604998],
  'G': [0.341635707],
  'H': [-0.17311034297999994]}}

In [6]:
# outFrame = pd.DataFrame(final_orientation*0.529177,columns = ['x','y','z'])
# outFrame['Atom'] = molecule_xyz['Atoms']
# outFrame = outFrame[['Atom','x','y','z']]
# with open('SubCH3_CFH2_anti2146_reor'+'reor.txt','w') as txt_file:
#     of_string = outFrame.to_string(header=False,index=False)
#     txt_file.write(of_string)
bcpPropDict = {}
origin_bcps = qt._find_connected(data,'H2','As1')
for bcp in origin_bcps:
        #bcpBlock = qt.lock()
        bcpPropDict.update({bcp[0]+'-'+bcp[1]: qt.get_bcp_properties(data,atPair=bcp)})
sr._find_clockwise_rot(bcpPropDict,'As1',atomDict['As1']['xyz'])

In [40]:
import numpy as np
originAtomLabel  ="As1"
negXAtomLabel="H2"

originAtomXYZ = atomDict['As1']['xyz']
atoms = list(atomDict.keys())
neg_x_index = atoms.index(negXAtomLabel)
crossDict = {}
for key1 in bcpPropDict:
    # print(key1)
    for key2 in bcpPropDict:
        # print(key2)
        if key1 != key2:
            to_rotate = np.vstack((originAtomXYZ,atomDict[negXAtomLabel]['xyz'],bcpPropDict[key1]['xyz'],bcpPropDict[key2]['xyz']))
            orig_geom = sr._set_origin(to_rotate,1)
            rot_geom = sr._set_xaxis(orig_geom,neg_x_index+1)
            zero_3d = np.array([0.0,0.0,0.0])
            bcp_1_xyz = rot_geom[2]
            bcp_2_xyz = rot_geom[3]
            bcp_2_xyz[0] = 0.
            bcp_1_xyz[0] = 0.
            cross=np.cross(bcp_1_xyz,bcp_2_xyz)[0]
            if cross < 0:
                isClockwise = True
            else:
                isClockwise = False
            if isClockwise:
                tempDict={'Is Clockwise':isClockwise,'cross':cross}
                bondAt1 = key1.replace(originAtomLabel+'-','')
                bondAt1 = bondAt1.replace('-'+originAtomLabel,'')
                bondAt2 = key2.replace(originAtomLabel+'-','')
                bondAt2 = bondAt2.replace('-'+originAtomLabel,'')
                crossDict.update({bondAt1 + '-To-' + bondAt2:tempDict})

In [42]:
orderDict= {}                
for cw in crossDict:
    string = cw.split('-')
    start = string[0]
    end = string[2]
    orderDict.update({cw:{'Start':start,'End':end}})
keysList = list(orderDict.keys())
if len(keysList) == 3:
    if orderDict[keysList[0]]['End'] != orderDict[keysList[1]]['Start'] and orderDict[keysList[0]]['End'] == orderDict[keysList[2]]['Start']:
        reordered_dict = {k : orderDict[k] for k in [keysList[0],keysList[2],keysList[1]]}
    else:
        reordered_dict = orderDict
    ordered_bcp_props = {}
    for order in reordered_dict:
        for bcp in bcpPropDict:
            # print(bcp)
            if reordered_dict[order]['Start'] in bcp:
                ordered_bcp_props.update({bcp:bcpPropDict[bcp]})
                continue
else:
    ordered_bcp_props = bcpPropDict

In [2]:
sr.rotate_substituent('SubH_AsO-C6H5-2_wb97xd_aug-cc-pvtz',1,2)

Atom         x             y             z
0   As1  0.000000  0.000000e+00  0.000000e+00
1    H2 -1.517390  3.561411e-18 -4.954641e-18
2    C3  0.478976  4.746434e-01 -1.808002e+00
3    C4  1.219875  1.634113e+00 -1.988086e+00
4    C5  0.114267 -3.050532e-01 -2.898456e+00
5    C6  1.592125  2.016978e+00 -3.268401e+00
6    H7  1.502410  2.221365e+00 -1.123553e+00
7    C8  0.487552  8.212875e-02 -4.175109e+00
8    H9 -0.450130 -1.218942e+00 -2.759726e+00
9   C10  1.225286  1.243452e+00 -4.358734e+00
10  H11  2.170332  2.919112e+00 -3.413424e+00
11  H12  0.207059 -5.228895e-01 -5.026318e+00
12  H13  1.517171  1.543324e+00 -5.356002e+00
13  C14  0.417931 -1.867472e+00  2.160341e-01
14  C15 -0.443344 -2.858855e+00 -2.357669e-01
15  C16  1.618988 -2.205275e+00  8.254203e-01
16  C17 -0.095678 -4.193110e+00 -9.055847e-02
17  H18 -1.391929 -2.598541e+00 -6.902678e-01
18  C19  1.961876 -3.540336e+00  9.702793e-01
19  H20  2.269767 -1.423164e+00  1.195018e+00
20  C21  1.107809 -4.531798e+00  5.097327e-01
21  H22 -0.765839 -4.966947e+00 -4.387884e-01
22  H23  2.894837 -3.807662e+00  1.446954e+00
23  H24  1.377387 -5.572649e+00  6.256928e-01
24  O25  0.707008  9.776043e-01  1.095005e+00

In [35]:
np.subtract(bcpPropDict['As1-C3']['xyz'],originAtomXYZ)

array([-1.36577277,  1.0509418 ,  0.34688541])

In [12]:
# sr._get_ref_bcps('SubH_NHOCH3_wb97xd_aug-cc-pvtz_reor',[['N1','H3'],['N1','O4'],['N1','C5']],originAtom='N1')

In [13]:
# sr._get_ref_bcps('SubH_POCH3H_wb97xd_aug-cc-pvtz_reor',[['P1','H3'],['P1','O4'],['P1','C5']],originAtom='P1')

In [14]:
# sr._get_ref_bcps('SubH_SiFHCH3_wb97xd_augccpvtz_reor',[['Si1','H3'],['Si1','C4'],['Si1','F8']],originAtom='Si1')

In [15]:
# sr._get_ref_bcps('SubH_Si2H3_wb97xd_augccpvtz_reor',[['Si1','H3'],['Si1','NNA7']],originAtom='Si1')

In [4]:
sr._get_ref_bcps('SubH_SeMeONH_wb97xd_aug-cc-pvtz_reor',[['Se1','C3'],['Se1','N8'],['Se1','O7']],originAtom='Se1')

{'Se1-C3': {'xyz': array([ 0.        ,  1.87292349, -0.00307118]),
  'rho': [0.17121305614],
  'lambda1': [-0.25262510465],
  'lambda2': [-0.2431461396],
  'lambda3': [0.2389715708],
  'DelSqRho': [-0.25679967346],
  'Ellipticity': [0.038984641362],
  'V': [-0.15993907718],
  'G': [0.047869579409],
  'H': [-0.112069497771]},
 'Se1-O7': {'xyz': array([ 0.        , -0.57902732, -1.28338305]),
  'rho': [0.24929577115],
  'lambda1': [-0.36655764455],
  'lambda2': [-0.35856712454],
  'lambda3': [1.146100412],
  'DelSqRho': [0.42097564287],
  'Ellipticity': [0.02228458625],
  'V': [-0.5649563289],
  'G': [0.33510011981],
  'H': [-0.22985620909000004]},
 'Se1-N8': {'xyz': array([ 0.        , -0.48606581,  1.35825466]),
  'rho': [0.22878600385],
  'lambda1': [-0.33066658688],
  'lambda2': [-0.27699185612],
  'lambda3': [0.59441734467],
  'DelSqRho': [-0.013241098322],
  'Ellipticity': [0.19377728828],
  'V': [-0.39582039171],
  'G': [0.19625505856],
  'H': [-0.19956533315]}}

In [5]:
sr._get_ref_bcps('SubH_NHCHO_wb97xd_aug-cc-pvtz_reor',[['N1','C3'],['N1','H6']],originAtom='N1')

{'N1-C3': {'xyz': array([ 0.00000000e+00, -1.39542332e+00, -1.63761637e-04]),
  'rho': [0.32693718717],
  'lambda1': [-0.75650210621],
  'lambda2': [-0.675516979],
  'lambda3': [0.5041288038],
  'DelSqRho': [-0.92789028141],
  'Ellipticity': [0.11988614606],
  'V': [-0.72612870727],
  'G': [0.24707806846],
  'H': [-0.47905063881]},
 'N1-H6': {'xyz': array([ 0.00000000e+00,  1.23859842e+00, -4.21801720e-07]),
  'rho': [0.35030375012],
  'lambda1': [-1.4125985037],
  'lambda2': [-1.353382837],
  'lambda3': [0.78134417668],
  'DelSqRho': [-1.984637164],
  'Ellipticity': [0.043753818271],
  'V': [-0.6055145775],
  'G': [0.054677643257],
  'H': [-0.5508369342430001]}}

In [6]:
sr._get_ref_bcps('SubH_AsSHMe_wb97xd_aug-cc-pvtz_reor',[['As1','H3'],['As1','C5'],['As1','S4']],originAtom='As1')

{'As1-H3': {'xyz': array([0.00000000e+00, 1.66597311e+00, 2.92243050e-05]),
  'rho': [0.16074222311],
  'lambda1': [-0.26271292349],
  'lambda2': [-0.26116539351],
  'lambda3': [0.35756172744],
  'DelSqRho': [-0.16631658956],
  'Ellipticity': [0.0059254787141],
  'V': [-0.2069227902],
  'G': [0.082671821405],
  'H': [-0.12425096879500001]},
 'As1-S4': {'xyz': array([ 0.        , -1.00964501, -1.4050059 ]),
  'rho': [0.14424198475],
  'lambda1': [-0.13762345197],
  'lambda2': [-0.13693770458],
  'lambda3': [0.17612393365],
  'DelSqRho': [-0.098437222899],
  'Ellipticity': [0.0050077324652],
  'V': [-0.15257163134],
  'G': [0.063981162807],
  'H': [-0.08859046853300001]},
 'As1-C5': {'xyz': array([ 0.        , -0.48601905,  1.67157541]),
  'rho': [0.14902610978],
  'lambda1': [-0.19377250142],
  'lambda2': [-0.19013450121],
  'lambda3': [0.26002921052],
  'DelSqRho': [-0.12387779211],
  'Ellipticity': [0.019133824683],
  'V': [-0.15906181002],
  'G': [0.064046180998],
  'H': [-0.09501562

In [5]:
amide_rot = sr.rotate_substituent('SubH_NHCHO_wb97xd_aug-cc-pvtz',1,2,6)
sr.output_to_gjf('SubH_NHCHO_wb97xd_aug-cc-pvtz',amide_rot)

In [6]:
se_rot = sr.rotate_substituent('SubH_SeOHMe_wb97xd_aug-cc-pvtz',1,7,2)
sr.output_to_gjf('SubH_SeOHMe_wb97xd_aug-cc-pvtz',se_rot)

In [2]:
ge_rot = sr.rotate_substituent('SubH_GeFHCH3_reor_wb97xd_aug-cc-pvtz',8,1,2)
sr.output_to_gjf('SubH_GeFHCH3_reor_wb97xd_aug-cc-pvtz',ge_rot)

In [8]:
as_rot = sr.rotate_substituent('SubH_AsSHMe_wb97xd_aug-cc-pvtz',1,2,3)
sr.output_to_gjf('SubH_AsSHMe_wb97xd_aug-cc-pvtz',as_rot)

In [3]:
se2_rot = sr.rotate_substituent('SubH_SeMeONH_wb97xd_aug-cc-pvtz',1,2,3)
sr.output_to_gjf('SubH_SeMeONH_wb97xd_aug-cc-pvtz',se2_rot)

In [3]:
s_rot = sr.rotate_substituent('SubH_SMeONH_wb97xd_aug-cc-pvtz',1,2,6)
sr.output_to_gjf('SubH_SMeONH_wb97xd_aug-cc-pvtz',s_rot)

In [4]:
start_geom = qt.get_xyz('SubH_AlFH_wb97xd_aug-cc-pvtz')

['Atom', 'Charge', 'X', 'Y', 'Z']


In [9]:
zero_orig = sr._set_origin(start_geom['xyz'],originAtom=1)

In [11]:
neg_x = sr._set_xaxis(zero_orig,negXAtom=2)

no way


In [12]:
neg_x

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.97307012e+00,  4.78467950e-49, -1.02646086e-16],
       [ 1.75146130e+00,  3.24547159e-16, -2.40240073e+00],
       [ 1.42224815e+00, -9.75941622e-33,  2.79697555e+00]])

In [13]:
start_geom['Atoms']

0    Al1
1     H2
2     H3
3     F4
Name: Atom, dtype: object

In [18]:
import numpy as np
G = np.array([[1,0,0],[0,0,-1],[0,1,0]])

In [19]:
G

array([[ 1,  0,  0],
       [ 0,  0, -1],
       [ 0,  1,  0]])

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.97307012e+00,  1.02646086e-16,  4.78467950e-49],
       [ 1.75146130e+00,  2.40240073e+00,  3.24547159e-16],
       [ 1.42224815e+00, -2.79697555e+00, -9.75941622e-33]])

In [22]:
pd.DataFrame(np.matmul(G, neg_x.T).T*0.529177)

0             1             2
0  0.000000  0.000000e+00  0.000000e+00
1 -1.573280  5.431795e-17  2.531942e-49
2  0.926833  1.271295e+00  1.717429e-16
3  0.752621 -1.480095e+00 -5.164459e-33

In [3]:
sr._get_ref_bcps('SubH_AlFH_wb97xd_aug-cc-pvtz_reor',[['Al1','H3'],['Al1','F4']],'Al1')

didnt find first
Al1-H3
Al1-H3
Al1-F4
Al1-F4
Al1-H3
Al1-F4


{'Al1-H3': {'xyz': array([0.00000000e+00, 1.20114665e+00, 4.34070797e-16]),
  'rho': [0.085283840331],
  'lambda1': [-0.13023736244],
  'lambda2': [-0.12418303897],
  'lambda3': [0.5104021269],
  'DelSqRho': [0.25598172549],
  'Ellipticity': [0.048753223633],
  'V': [-0.12032196192],
  'G': [0.092158696644],
  'H': [-0.028163265275999994]},
 'Al1-F4': {'xyz': array([ 0.00000000e+00, -1.20452018e+00,  1.63687220e-16]),
  'rho': [0.10796739991],
  'lambda1': [-0.22563832606],
  'lambda2': [-0.22151270398],
  'lambda3': [1.4608614277],
  'DelSqRho': [1.0137103977],
  'Ellipticity': [0.01862476509],
  'V': [-0.25888054711],
  'G': [0.25615407326],
  'H': [-0.002726473850000022]}}

In [5]:
sr.rotate_substituent('SubH_AsO-C6H5-2_wb97xd_aug-cc-pvtz',1,2)

UnboundLocalError: cannot access local variable 'retDict' where it is not associated with a value

In [36]:
np.vstack(np.array([1,0,0],[0,1,0],[0,0,1]))

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [3]:
sr._get_ref_bcps('SubH_GeFHCH3_reor_wb97xd_aug-cc-pvtz_reor',[['Ge1','H3'],['C4','Ge1'],['Ge1','F8']],'Ge1','H2')

{'Ge1-H3': {'xyz': array([0.63285749, 1.58759917, 0.00208131]),
  'rho': [0.13950861934],
  'lambda1': [-0.2238517257],
  'lambda2': [-0.21714809643],
  'lambda3': [0.44525117602],
  'DelSqRho': [0.004251353896],
  'Ellipticity': [0.030871232028],
  'V': [-0.18643355305],
  'G': [0.093748195763],
  'H': [-0.092685357287]},
 'Ge1-F8': {'xyz': array([ 0.41813183, -0.61659892, -1.38436273]),
  'rho': [0.14029849101],
  'lambda1': [-0.2372955179],
  'lambda2': [-0.23697268425],
  'lambda3': [1.2175270474],
  'DelSqRho': [0.74325884528],
  'Ellipticity': [0.0013623243216],
  'V': [-0.30800281487],
  'G': [0.24690876309],
  'H': [-0.061094051779999964]},
 'C4-Ge1': {'xyz': array([ 0.69530554, -1.02534523,  1.22952605]),
  'rho': [0.13510538184],
  'lambda1': [-0.17101376836],
  'lambda2': [-0.16586123104],
  'lambda3': [0.36947775438],
  'DelSqRho': [0.032602754982],
  'Ellipticity': [0.031065350768],
  'V': [-0.16485750895],
  'G': [0.08650409885],
  'H': [-0.0783534101]}}

In [4]:
sr._get_ref_bcps('SubH_SMeONH_wb97xd_aug-cc-pvtz_reor',[['S1','N3'],['S1','C6'],['S1','O5']], 'S1', 'H2')

{'S1-N3': {'xyz': array([ 0.41409652, -0.40317651,  0.97579674]),
  'rho': [0.29061950428],
  'lambda1': [-0.47197082176],
  'lambda2': [-0.38837775089],
  'lambda3': [0.8453128352],
  'DelSqRho': [-0.015035737458],
  'Ellipticity': [0.21523650796],
  'V': [-0.81533309495],
  'G': [0.40578708029],
  'H': [-0.40954601465999996]},
 'S1-C6': {'xyz': array([0.29635447, 1.79135009, 0.00210556]),
  'rho': [0.21337516588],
  'lambda1': [-0.37287781693],
  'lambda2': [-0.36051618073],
  'lambda3': [0.28532870563],
  'DelSqRho': [-0.44806529203],
  'Ellipticity': [0.034288713947],
  'V': [-0.20762767474],
  'G': [0.047805675864],
  'H': [-0.159821998876]},
 'S1-O5': {'xyz': array([ 0.27136246, -0.43072436, -0.95096459]),
  'rho': [0.29999597907],
  'lambda1': [-0.5103763232],
  'lambda2': [-0.48629716874],
  'lambda3': [1.8841002159],
  'DelSqRho': [0.88742672394],
  'Ellipticity': [0.049515308766],
  'V': [-1.0036074399],
  'G': [0.61273206043],
  'H': [-0.39087537946999995]}}